In [14]:
# Numpyをインポートするコード
import numpy as np

# AとBの行列を格納する多次元配列
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

# 行列の積を計算
C = np.dot(A, B)

# 計算結果を表示
print(C)

# 行列の要素の最大値
max_value = np.max(C)
print(max_value)


[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
